### PR TITLE
Added new lock test for lock do i hold and lock release

### PR DESCRIPTION
**Pull request by zsmoore**
It is possible to receive full credit for locks without actually having properly implemented locks.

If you implement locks with a boolean for whether the lock is held or not rather than holding a thread you will almost always pass the test suite if your lock do I hold returns only that boolean.

Even though locktest1 says it checks ownership properly, 9/10 times you will receive full credit for locks with only a boolean.

- Added a new lock test that has one thread acquire then another thread call lock do i hold and will fail if thread 2 returns true.
- Also second thread calls lock release, if release is allowed to go through test fails, if release panics, test is a success as we have already checked lock do i hold functionality.
- Added new lock test to main menu as well.

Tested on lock implementation using boolean and every test passes but the new test fails.
Tested on correct lock implementation and the test passes.

Currently hard coded for only 2 threads to be created however, the test **should** work correctly with any number of threads created.

Without this test an implementation in which any thread can release a lock regardless of ownership will be able to receive full credit on ASST1.

**Comments currently exist in test code to allow reviewer to understand what is happening.  The comments should be removed before merging.**

**Note:** If accepted will need to be put into test161 still.

### CODE REVIEW

**Comment by gchallen** [comment]
Thanks for the changes. I've merged them, although I had to do a fair amount of work to rewrite the tests. Next time please follow our formatting standards.

There was also no need for these tests to fork two threads. I've modified them to have the main driver thread act as the alternate thread.

But thanks again for pointing out the holes in our test coverage. Much appreciated.

**Comment by gchallen** [comment]
Also: extra credit applied. If you want to share this with your partner, identify them and let me know. At this point these tests aren't yet part of test161's asst1 target, but we'll get them there. (We need to rework some of the dependencies and point allocations with existing tests.)

**Comment by zsmoore** [comment]
The changes to my test look great.

I was going to integrate into the previous locktestthread however I tried to interweave the code as little as possible which doesn't make sense to do now that I think of it.

Also apologies for not isolating the functionality of the new test to 2 individual tests and adding the extra work. I meant to do so over this past weekend but did not have time.

If there is anything else regarding the code you would like me to help out with let me know.

**Comment by gchallen** [comment]
No worries—thanks for the help. (Also next time be careful to respect the original tabs and spaces settings.)

**Pull request merged**
